Gf 207 article rud
The-Avengers-Gamera/gamera-be pull request #32
Opened 2023-02-26 10:46 UTC by L-DENG

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +import org.springframework.web.bind.annotation.*;
Don't use wild card import

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    @PatchMapping("/{articleId}")
Usr `PUT` instead of `PATCH`

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    public ArticleGetDto updateArticle(@RequestBody ArticlePatchDto articlePatchDto, @PathVariable Long articleId){
Why do we need to individually set articleId as path variable rather than directly put it in the request body?

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    @GetMapping("/pages")
What does this URI stand for?

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    public List<MiniArticleGetDto> getMiniArticlesByType(@PathVariable ArticleType articleType, Integer pageNumber, Integer pageSize){
Use RequestParam instead

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/dto/article/ArticleGetDto.java
> +    private Game game;
Should we directly put entity in dtos?

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/dto/article/ArticlePatchDto.java
> +    @Enumerated(EnumType.STRING)
This annotation seems not needed here.

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/dto/article/ArticlePostDto.java
> +    @NotBlank(message = "gameId must be provided.")
It's only for `String`

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/dto/article/ArticlePostDto.java
> +    @NotBlank(message = "authorId must be provided.")
Same

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/dto/article/MiniArticleGetDto.java
> +//    private Long numberOfComments;
Are they still needed? If not, just remove.

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/entity/Article.java
> +
Why do we need `CascadeType.PERSIST` here?

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +                new ResourceNotFoundException("Related game")
Exception messages should be in detail. Also, logging is also necessary.

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        log.info("==========Saving new article to database==============");
Is it informative or useful?

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        log.info("Try to get some articles that has not been deleted .....");
Logging is supposed to be meaningful.

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +            return null;
Never return `null`, as it can lead to potential issues.

2023-02-26 11:41 UTC, LawrenceLiao commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        articleRepository.delete(article);
Do not literally delete a record from db. We have an attribute named `deleted` or `isDeleted` to implement soft deleting. Besides, even if you do delete it from db, you should not talk to Database twice.

2023-02-28 12:47 UTC, weited requested changes

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    @PutMapping("/update")
restful design  please

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    @GetMapping("/pages/{pageNumber}/{pageSize}")
please follow the api document design. use query instead of path param

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/entity/Article.java
> +import javax.persistence.*;
why replace the import

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/entity/Article.java
> +    @Column(name = "is_deleted")
no necessary

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/entity/Game.java
> +    @OneToMany(cascade = CascadeType.PERSIST)
PERSIST no need here

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        log.info("Saving new article: "+article.toString()+" ======>>to database");
why log all the article text?

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +    public void deleteArticleById(Long articleId) {
if you log other actions,  the deletion action is more important to have a log such as article id, who and when deleted this article

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        article.setGame(game);
have you done test?  can this step be done?

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    @GetMapping("/types/{articleType}/{pageNumber}/{pageSize}")
same

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    public ArticleGetDto createArticle(@PathVariable Long articleId) {
please use appropriate name

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    public ArticleGetDto updateArticle(@RequestBody ArticlePatchDto articlePatchDto){
you use @PutMapping, then why patch here

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/dto/article/ArticleGetDto.java
>      private String coverImgUrl;
have you tested?  can you get those filed from response

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/repository/ArticleRepository.java
> +    List<Article> findArticleByIsDeletedFalse(Pageable pageable);
Have you tested?

2023-02-28 12:47 UTC, weited commented on src/main/java/com/avengers/gamera/repository/ArticleRepository.java
> +    List<Article> findArticlesByTypeAndIsDeletedFalse(ArticleType articleType, Pageable pageable);
Return page information please

2023-03-02 13:24 UTC, merged