Gf 393 update database table
The-Avengers-Gamera/gamera-be pull request #53
Opened 2023-03-08 16:47 UTC by HUHANG716

2023-03-09 05:42 UTC, weited reviewed
两行sql 完全可以合并在一个V13就够了啊 (只是评论)

2023-03-09 05:42 UTC, weited commented on src/main/resources/db/migration/V14__add_subtitle_to_article_table.sql
> +ALTER TABLE "article" ADD subtitle VARCHAR(255) NOT NULL;
这个地方确认了 是要NOT NULL吗

2023-03-09 22:14 UTC, weited requested changes

2023-03-09 22:14 UTC, weited commented on src/main/resources/db/migration/V13__add_column_to_game_table_and_article_table.sql
> +ALTER TABLE "game" ADD img_url VARCHAR(255);
好像是不是弄反了  问下 @JennieZhu29

2023-03-11 08:54 UTC, JennieZhu29 commented on src/main/resources/db/migration/V13__add_column_to_game_table_and_article_table.sql
> +ALTER TABLE "game" ADD img_url VARCHAR(255);
NOT NULL反过来哈

2023-03-11 09:20 UTC, weited approved these changes

2023-03-11 09:20 UTC, merged