Gf 299 reviews and pagination
The-Avengers-Gamera/gamera-be pull request #54
Opened 2023-03-08 18:45 UTC by HUHANG716

2023-03-11 08:41 UTC, weited requested changes

2023-03-11 08:41 UTC, weited commented on src/main/java/com/avengers/gamera/controller/NewsController.java
> +    @GetMapping("/platforms/{platform}")
不需要这个接口   这个filter 放在news 那边内部  用query 来查询

2023-03-11 08:41 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ReviewController.java
> +    @GetMapping("/platforms/{platform}")
同上

2023-03-12 05:43 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ArticleController.java
> +    public PagingDto<Object> getNews(@RequestParam(defaultValue = "1") int page,
处理conflict删错了?

2023-03-12 05:43 UTC, weited commented on src/main/java/com/avengers/gamera/controller/ReviewController.java
> +import org.springframework.web.bind.annotation.*;
恢复下这个文件?

2023-03-12 05:43 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +                .orElse(articleRepository.findArticlesByTypeAndIsDeletedFalse(articleType, pageable));
platform进来应该是 空的字符串  不是null ?     还有 如果是 'all'  的话呢?

2023-03-12 05:43 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +
+ 四个空行?

2023-03-12 05:43 UTC, weited commented on src/main/java/com/avengers/gamera/service/GameService.java
> +        String platform=Optional.ofNullable(gamePostDto.getPlatform()).orElse("unknown platform");
为什么改这个?

2023-03-12 09:04 UTC, HUHANG716 commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +                .orElse(articleRepository.findArticlesByTypeAndIsDeletedFalse(articleType, pageable));
不设defaultvalue 不填platform就是null。all的话就查不出东西，如果你是指查所有的平台的文章话就不填platform就是查所有平台了呀

2023-03-12 10:04 UTC, HUHANG716 commented on src/main/java/com/avengers/gamera/service/GameService.java
> +        String platform=Optional.ofNullable(gamePostDto.getPlatform()).orElse("unknown platform");
我想把它转小写，但是我怕它空指针

2023-03-12 10:07 UTC, HUHANG716 commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +                .orElse(articleRepository.findArticlesByTypeAndIsDeletedFalse(articleType, pageable));
哦哦我好像明白你意思了，那我改改吧

2023-03-12 10:19 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +                .orElse(articleRepository.findArticlesByTypeAndIsDeletedFalse(articleType, pageable));
嗯嗯 反正都是可以讨论的 主要是定一个 前后都改掉

2023-03-12 10:27 UTC, weited commented on src/main/java/com/avengers/gamera/service/GameService.java
> +        String platform=Optional.ofNullable(gamePostDto.getPlatform()).orElse("unknown platform");
哦哦 你是想存入的时候 转换成小写是吧  
之前是考虑这里用enum来限定的 除了枚举外的都都直接返回404
不过我们现在前端没有game的写入界面 可以先不管的.  
api的话 platform本来就可以为空的 要不存一个空string?  
```suggestion
        String platform=Optional.ofNullable(gamePostDto.getPlatform()).orElse("");
```
这个能写入吗?

2023-03-12 10:31 UTC, weited commented on src/main/java/com/avengers/gamera/service/GameService.java
> +        String platform=Optional.ofNullable(gamePostDto.getPlatform()).orElse("unknown platform");
而且这里是拼接值  'pc,xbox'  这样的  所以本来就比较随意  就只是为了查询而已 所以真要严格 还得一个个检查 然后自己拼起来

2023-03-12 13:40 UTC, weited approved these changes

2023-03-12 13:40 UTC, weited commented on src/main/java/com/avengers/gamera/service/ArticleService.java
> +        articlePage = platform.equals("all")
噢  你这样设计也挺好的 👍    都不用改前端了

2023-03-12 14:53 UTC, merged