GF-435-user-table-init
The-Avengers-Gamera/gamera-be pull request #57
Opened 2023-03-10 05:59 UTC by RoRobinh98

2023-03-10 09:22 UTC, JennieZhu29 commented on src/main/resources/db/migration/V15__init_user.sql
> +INSERT INTO "user" (email, name, password, is_verified)
user 要加双引号吗

2023-03-10 09:23 UTC, JennieZhu29 commented on src/main/resources/db/migration/V15__init_user.sql
> +VALUES ('gamera.newseditor1@gmail.com', 'newseditor1', 'pwdnewseditor1', true),
密码要求至少8位，并含一个非letter

2023-03-11 08:41 UTC, weited requested changes
这应该没测试过 账号登录不上吧?

- 密码明文  

- 没有赋予权限

2023-03-12 00:48 UTC, weited commented
把你的branch 本地合并了, 然后rebase到develop(或者merge )   然后重新强制push上来

2023-03-12 00:49 UTC, weited requested changes

2023-03-12 00:49 UTC, weited commented on src/main/resources/db/migration/V15__init_user.sql
> +VALUES (1, 4),
你无法保证 在其他环境下  这个user id 还是1, 2,3,4

2023-03-12 00:49 UTC, weited commented on src/main/resources/db/migration/V15__init_user.sql
> +       (8, 1);
每个用户 都默认自带了  USER权限

2023-03-12 05:21 UTC, merged